### ISSUE TITLE
处理 vue 文件的 template、style、script 标签使用预处理器时产生的问题

### ISSUE THREAD

**Issue by Dafrok** [ecomfe/fecs-loader#9]
### 现象
当 vue 文件的 template、style、script 标签使用 lang 属性时，fecs-loader 不能正确地处理预处语言的语法。

### 源码
```vue
<template lang="pug">
div
    span foo
</template>

<style lang="stylus">
body
    margin 0
</style>
```

### 错误信息
```bash
fecs  WARN → line 3, col 1: Line should indent with 4 spaces.
fecs  WARN → line 8, col 1: CssSyntaxError: <css input>:3:1: Unknown word
```

**Comment by zhangzhiqiang37** [comment]
这种场景不支持，fecs里也没计划支持

**Comment by Dafrok** [comment]
应该有个方法能够全局性地检查.vue文件中 script 标签，并忽略 style 和 template 标签，现在要么逐个加注释要么直接忽略 .vue 感觉姿势似乎不太对。

**Comment by Justineo** [comment]
@chriswong @ielgnaw 看一下 FECS 是否可以计划支持这种场景？

**Comment by otakustay** [comment]
我也建议有办法在`<style>`或`<template>`之类上添加`fecs-ignore="*"`之类的属性控制

**Comment by zhangzhiqiang37** [comment]
fecs已支持vue类型文件
